name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify Firebase secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then
            echo "Error: FIREBASE_API_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.FIREBASE_AUTH_DOMAIN }}" ]; then
            echo "Error: FIREBASE_AUTH_DOMAIN is not set"
            exit 1
          fi
          echo "Firebase secrets verification completed"

      - name: Create Firebase Config
        run: |
          cat > js/firebase-config.js << 'EOL'
          // Firebase configuration - Auto-generated by GitHub Actions
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };

          // Initialize Firebase
          if (!firebase.apps.length) {
              firebase.initializeApp(firebaseConfig);
          } else {
              firebase.app();
          }

          // Initialize services
          const auth = firebase.auth();
          const db = firebase.firestore();
          const storage = firebase.storage();
          const rtdb = firebase.database();

          // Enable persistence
          db.enablePersistence()
              .catch((err) => {
                  if (err.code === 'failed-precondition') {
                      console.log('Multiple tabs open, persistence can only be enabled in one tab at a time.');
                  } else if (err.code === 'unimplemented') {
                      console.log('The current browser does not support persistence.');
                  }
              });

          // Configure Firestore settings
          db.settings({
              cacheSizeBytes: firebase.firestore.CACHE_SIZE_UNLIMITED
          });
          EOL

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 